version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: veterinaria
      POSTGRES_USER: alumno
      POSTGRES_PASSWORD: alumno123
    ports:
      - "3322:3322"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    ports:
      - "7777:7777"
    depends_on:
      - db
    environment:
      #DATABASE_URL: postgresql://alumno:alumno123@db/veterinaria
      DATABASE_URL: postgresql://alumno:alumno123@db/veterinaria

volumes:
  pgdata:
