name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 44022
          script: |
            set -e
            # adjust this path to where your repo is on the VPS
            cd /root/API-Vet
            git pull origin main
            # If you use docker-compose to run the app, rebuild and restart
            if command -v docker-compose >/dev/null 2>&1; then
              docker-compose pull || true
              docker-compose up -d --build
            else
              # fallback: run a git-based deploy (adjust to your service)
              echo "docker-compose not found on remote. Update script to suit your deploy method."
            fi
