name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_SSH_PORT }}
          passphrase: ${{ secrets.VPS_SSH_PASSPHRASE }}
          script: |
            set -e
            cd /root/API-Vet
            git pull origin main

            # Prefer Docker Compose v2 (docker compose). If not available, fall back to docker-compose.
            if docker compose version >/dev/null 2>&1; then
              docker compose down --remove-orphans || true
              docker compose up -d --build --remove-orphans
            else
              docker-compose down --remove-orphans || true
              docker-compose up -d --build --remove-orphans
            fi
